### PR TITLE
Mobile Browsers: Update : Onion --> Tor

### PR DESCRIPTION
**Pull request by hpnightowl**
*Since we Got a Stable Tor Browser So Why Onion Now

### CODE REVIEW

**Comment by hpnightowl** [comment]
I Will Recommend To Everyone Your Website Is awesome

**Comment by hpnightowl** [comment]
@danarel r u merging it?

**Comment by danarel** [comment]
Onion is the iOS browser. There is no Tor Browser for iOS. At this point, we don't recommend Android apps as we don't recommend people use Android. Tor recommends users use Onion on iOS.

We could expand to an iOS and Android app section.

**Comment by hpnightowl** [comment]
ok @danarel

**Comment by danarel** [comment]
> ok @danarel will be great to expand it since android users are more

Under OS, we give alternative recommendations for Android users:
https://www.thinkprivacy.io/#os

However, I am not against adding iOS and Android app sections, however, I would stipulate all Android apps would need to be available through the F-Droid store or direct APK, nothing linked to the Google Play Store.

**Comment by hpnightowl** [comment]
ok i have a suggestion  we can do one thing instead of making other section (which new people may not find) we can add that it is available at google play/ fdroid/ ios like this stuff

**Comment by danarel** [comment]
Added a platform section, and added both Onion and Tor for mobile.

**Comment by hpnightowl** [comment]
ok

**Pull request closed without merging**
